[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "qmgwiki"
authors = [{name = "McStudently", email = "quantum-materials-group@physicist.net"}]
dynamic = ["version", "description"]
